# **Biblioteca NumPy:**

[Site do NumPy](https://numpy.org/)

In [ ]:
import numpy as np
a = np.array([12,34,26,18,10])
# cria uma matriz unidimensional
print(a)
print(a.dtype)

a1 = np.array([1, 2, 3], dtype = np.float64)
# cria o array como float de 64 bits
print(a1)
print(a1.dtype)

a2 = np.array([1, 2, 3], dtype = np.int32)
# cria o array como float de 64 bits
print(a2)
print(a2.dtype)

[12 34 26 18 10]
int64
[1. 2. 3.]
float64
[1 2 3]
int32


In [ ]:
#Python puro versus python+numpy 
mat = [[7,2,23],[12,27,4],[5,34,23]]
print(mat, "\n")

b = np.array([[7,2,23],[12,27,4],[5,34,23]])
# cria um matriz bidimensional
print(b)

[[7, 2, 23], [12, 27, 4], [5, 34, 23]] 

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


**Algumas matrizes especiais, muito úteis:**

In [ ]:
d = np.zeros([4,3])
# cria uma matriz 4x3 com valores zero
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
e = np.ones([5,7])
# cria uma matriz de 5x7 com valores 1
print(e)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Matriz identidade:

In [ ]:
f = np.eye(5)
# cria matriz quadrada com diagonal principal com valores 1 e os outros valores zero
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Matriz preenchida com números aleatórios:

In [ ]:
g = np.random.random((5))
print(g, "\n")

h = 10*np.random.random((3,4))
print(h, "\n")

h = np.floor(h)
print(h, "\n")

#Vamos gerar um vetor com aleatório de -0,9999 a +0,9999
h = 2*np.random.random((3,4)) - 1
print("Aleatórios de -0,999 a +0,999:\n")
print(h, "\n")
print("Média de h:", h.mean())
print("Mínimo de h:", h.min())
print("Máximo de h:", h.max())

print("\nAleatórios seguindo a curva normal, com média 0 e desvio padrão 1:\n")
g2 = np.random.randn((10))
print(g2, "\n")
print("Média de g2:", g2.mean())
print("Mínimo de g2:", g2.min())
print("Máximo de g2:", g2.max())
print("Desvio padrão de g2:", g2.std())

[0.74536761 0.0793922  0.78673452 0.99980301 0.46708778] 

[[6.80303988 3.12169676 5.82259688 4.72610253]
 [3.50141341 4.80546637 9.65247452 1.11235511]
 [0.32329245 7.50153614 4.34783854 4.62137018]] 

[[6. 3. 5. 4.]
 [3. 4. 9. 1.]
 [0. 7. 4. 4.]] 

Aleatórios de -0,999 a +0,999:

[[-0.98823598 -0.0298347  -0.78191763 -0.81355724]
 [ 0.25736385 -0.9939052  -0.68189297 -0.84314668]
 [ 0.84858697 -0.49600177 -0.19701548 -0.02011747]] 

Média de h: -0.39497285869298154
Mínimo de h: -0.993905199452084
Máximo de h: 0.8485869705745039

Aleatórios seguindo a curva norma, com média 0 e desvio padrão 1:

[-1.46342285 -1.18721132 -1.07437223  0.30696832  0.1045317   0.80457497
 -0.1422762  -1.54768835  0.49319577 -0.12648861] 

Média de g2: -0.38321888098701223
Mínimo de g2: -1.5476883460096849
Máximo de g2: 0.8045749676362577
Desvio padrão de g2: 0.8163397705183738


Com o gerador de inteiros você pode gerar inteiros aleatórios indicando o valor inicial (lembre-
se de que isso é inclusivo com NumPy) até o valor final (exclusivo). Você pode definir
“endpoint = True” para tornar o valor final inclusivo. Veja o exemplo:

In [ ]:
gnr = np.random.default_rng(0)
i = gnr.integers(10, size=(3, 4))
print(i)

[[8 6 5 2]
 [3 0 0 0]
 [1 8 6 9]]


Já a função “unique” permite obtermos a quantidade de números em um array sem
repetições. Veja o exemplo:


In [ ]:
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


Funções para estatística: mínimo, máximo, média, desvio padrão

In [ ]:
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
# cria a matriz bidimensional k
print(k)
# Mostra a matriz k
print(k[0][1])
# Mostra um elemento específico da matriz k
print("Dimensões = ", k.shape)
# Mostra o tamanho das dimensões da matriz k
print("Máximo = ", k.max())
# Mostra o maior valor da matriz k
print("Mínimo = ", k.min())
# Mostra o menor valor da matriz k
print("Soma = ", k.sum())
# Mostra a soma dos valores da matriz k
print("Média = ", k.mean())
# Mostra o valor da média dos valores da matriz k
print("Desvio padrão = ", k.std())
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
Dimensões =  (3, 3)
Máximo =  43
Mínimo =  14
Soma =  219
Média =  24.333333333333332
Desvio padrão =  8.615231988880057


Raiz quadrada e exponenciação:

In [ ]:
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


Como extrair linhas e/ou colunas de arrays:

In [ ]:
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l, "\n")
l_linha_0 = l[0, :]
print("Extraindo a linha 0:", l_linha_0)
l_linha_1 = l[1, :]
print("Extraindo a linha 1:", l_linha_1)
l_linha_2 = l[2, :]
print("Extraindo a linha 2:", l_linha_2)
l_coluna_0 = l[:, 0]
print("Extraindo a coluna 0:", l_coluna_0)
l_coluna_1 = l[:, 1]
print("Extraindo a coluna 1:", l_coluna_1)

[[4 5]
 [6 1]
 [7 4]] 

Extraindo a linha 0: [4 5]
Extraindo a linha 1: [6 1]
Extraindo a linha 2: [7 4]
Extraindo a coluna 0: [4 6 7]
Extraindo a coluna 1: [5 1 4]


Além desse recurso de extração de linhas e colunas é possível realizar com os arrays do NumPy
todos os recursos de fatiamento que foram apresentados para listas em Python.

In [ ]:
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1])
# Mostra o elemento da posição 2
print(m[0:2])
# Mostra o array criado a partir da posição 0, dois elementos
print(m[1:])
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[-3:])
# Mostra o array criado a partir da antepenúltima
#posição até o final

2
[1 2]
[2 3 4 5 6]
[4 5 6]


Você pode adicioná-las e multiplicá-las usando operadores
aritméticos se tiver duas matrizes do mesmo tamanho.

In [ ]:
n = np.array([[1, 2], [3, 4], [6, 7]])
o = np.array([[1, 1], [1, 1], [-1, 0]])
res1 = n+o
print("Soma das duas matrizes 'n' e 'o':\n", res1)
res2 = n*o
print("Multiplicação (elemento por elemento) das duas matrizes 'n' e 'o':\n", res2)

Soma das duas matrizes 'n' e 'o':
 [[2 3]
 [4 5]
 [5 7]]
Multiplicação (elemento por elemento) das duas matrizes 'n' e 'o':
 [[ 1  2]
 [ 3  4]
 [-6  0]]


*Semelhança de cossenos:*

In [ ]:
import numpy as np
#vetores 1 e 2 são bem "parecidos" e o 3 é bem diferente dos outros 2
vetor1 = np.array([1, 0, 0, 1, 0, 1])
vetor2 = np.array([1, 1, 0, 1, 0, 1])
vetor3 = np.array([0, 0, 1, 0, 0, 0])

semelhanca = lambda v1, v2: np.dot(v1, v2)/(np.linalg.norm(v1)* np.linalg.norm(v2)) 
# = cosseno do ângulo entre os vetores v1 e v2 

print('Semelhança entre os vetores:')
print("Semelhança entre vetor1 e vetor2:", semelhanca(vetor1, vetor2))
print("Semelhança entre vetor1 e vetor3:", semelhanca(vetor1, vetor3))
print("Semelhança entre vetor2 e vetor3:", semelhanca(vetor2, vetor3))

Semelhança entre os vetores:
Semelhança entre vetor1 e vetor2: 0.8660254037844387
Semelhança entre vetor1 e vetor3: 0.0
Semelhança entre vetor2 e vetor3: 0.0


Transpor e rearranjar eixos é uma tarefa comum em processamento de dados e cálculos
numéricos.

In [ ]:
r = np.arange(15).reshape((3, 5))
# rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas.
print(r, "\n")
# mostra a matrizes transposta entre linha e coluna
s = r.T
print(s, "\n")
u = np.fliplr(s)
print(u)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 

[[10  5  0]
 [11  6  1]
 [12  7  2]
 [13  8  3]
 [14  9  4]]


Agora apresentaremos como usar expressões lógicas em array. O NumPy nos fornece a função
“where” que substitui um laço condicional if-else.

In [ ]:
v = np.random.randn(4, 4)
print(v, "\n")
# criando matriz com valores aleatórios positivos e negativos
x = (v > 0)
# criando matriz com valores booleanos baseado no array v
print(x)
z = np.where(x > 0, 1, -1)
# criando matriz com valores -1 e 1 baseado nos valores do array x
print(z)

[[ 0.55598624 -0.96254932  0.7927942  -0.22680034]
 [-1.61432137  0.51403825  0.61409056 -1.06498639]
 [-0.62066133  0.98148645 -0.10366548  1.02293418]
 [-1.84724286  1.97061507 -1.27209752 -0.03975242]] 

[[ True False  True False]
 [False  True  True False]
 [False  True False  True]
 [False  True False False]]
[[ 1 -1  1 -1]
 [-1  1  1 -1]
 [-1  1 -1  1]
 [-1  1 -1 -1]]


# **Pandas:**

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving Planilha_teste.xlsx to Planilha_teste.xlsx


In [ ]:
!ls

Planilha_teste.xlsx  sample_data


In [ ]:
import pandas as pd
dados1 = pd.read_excel('Planilha_teste.xlsx')
dados1

números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f
6        7      g
7        8      h
8        9      i
9       10      j

In [ ]:
!ls
files.download("Planilha_teste.xlsx")

Planilha_teste.xlsx  sample_data


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
print(dados1.shape)
print(dados1.head(),"\n")
print(dados1.head(10))

(10, 2)
   números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e 

   números letras
0        1      a
1        2      b
2        3      c
3        4      d
4        5      e
5        6      f
6        7      g
7        8      h
8        9      i
9       10      j


In [ ]:
print(dados1.tail())

   números letras
5        6      f
6        7      g
7        8      h
8        9      i
9       10      j


*Importando uma base sobre o Titanic (esta base está disponível no site Kaggle):*

https://www.kaggle.com/c/titanic/data?select=train.csv




In [ ]:
uploaded = files.upload()

Saving train.csv to train.csv


In [ ]:
!ls

Planilha_teste.xlsx  sample_data  train.csv


In [ ]:
dados2 = pd.read_csv('train.csv')
print(dados2.shape)
print(dados2.head(10))
print(dados2.describe())

(891, 12)
   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S
5            6         0       3  ...   8.4583   NaN         Q
6            7         0       1  ...  51.8625   E46         S
7            8         0       3  ...  21.0750   NaN         S
8            9         1       3  ...  11.1333   NaN         S
9           10         1       2  ...  30.0708   NaN         C

[10 rows x 12 columns]
       PassengerId    Survived      Pclass  ...       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  ...  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642  ...    0.523008    0.381594   32.204208
std     257.353842   

In [ ]:
uploaded = files.upload()
dados3 = pd.read_csv('census.csv')
print(dados3.shape)
print(dados3.head(10))
print(dados3.describe())

Saving census.csv to census.csv
(30162, 16)
   Unnamed: 0  age          workclass  ...  hour.per.week  native.country  income
0           1   39          State-gov  ...             40   United-States   <=50K
1           2   50   Self-emp-not-inc  ...             13   United-States   <=50K
2           3   38            Private  ...             40   United-States   <=50K
3           4   53            Private  ...             40   United-States   <=50K
4           5   28            Private  ...             40            Cuba   <=50K
5           6   37            Private  ...             40   United-States   <=50K
6           7   49            Private  ...             16         Jamaica   <=50K
7           8   52   Self-emp-not-inc  ...             45   United-States    >50K
8           9   31            Private  ...             50   United-States    >50K
9          10   42            Private  ...             40   United-States    >50K

[10 rows x 16 columns]
         Unnamed: 0           

In [ ]:
teste = pd.Series(range(0,101))
teste.describe()

count    101.000000
mean      50.000000
std       29.300171
min        0.000000
25%       25.000000
50%       50.000000
75%       75.000000
max      100.000000
dtype: float64

In [ ]:
alunos = {'Nome':['Marcelo','Lucas','Cynthia','Helena'],
'Media':[4,7,5.5,9],
'Status':['Reprovado','Aprovado','Reprovado','Aprovado']}

df1 = pd.DataFrame(alunos)
print(df1.shape)
print(df1.head())
print(df1.describe())

(4, 3)
      Nome  Media     Status
0  Marcelo    4.0  Reprovado
1    Lucas    7.0   Aprovado
2  Cynthia    5.5  Reprovado
3   Helena    9.0   Aprovado
          Media
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000


Filtrando colunas específicas do *dataframe*:

In [ ]:
print(df1[['Nome']])
print(type(df1[['Nome']]))

      Nome
0  Marcelo
1    Lucas
2  Cynthia
3   Helena
<class 'pandas.core.frame.DataFrame'>


Notem a diferença (vamos falar de *Series* daqui a pouco...):

In [ ]:
print(df1['Nome'])
print(type(df1['Nome']))

0    Marcelo
1      Lucas
2    Cynthia
3     Helena
Name: Nome, dtype: object
<class 'pandas.core.series.Series'>


Filtrando linhas com o *loc*:

In [ ]:
df1.loc[[1,3]] #linhas 1 e 3

Nome  Media    Status
1   Lucas    7.0  Aprovado
3  Helena    9.0  Aprovado

In [ ]:
df1.loc[1:3] #linhas 1 a 3

Nome  Media     Status
1    Lucas    7.0   Aprovado
2  Cynthia    5.5  Reprovado
3   Helena    9.0   Aprovado

Estabelecer condições:

In [ ]:
df1.loc[df1['Status'] == 'Aprovado']

Nome  Media    Status
1   Lucas    7.0  Aprovado
3  Helena    9.0  Aprovado

In [ ]:
df1.loc[df1['Media'] < 7.0]

Nome  Media     Status
0  Marcelo    4.0  Reprovado
2  Cynthia    5.5  Reprovado

Selecionando colunas:

In [ ]:
exame = df1[['Nome', 'Media']].loc[df1['Media'] < 7.0]
print(exame)

      Nome  Media
0  Marcelo    4.0
2  Cynthia    5.5


**Estatísticas sobre o Titanic:**

In [ ]:
homens = dados2[['Survived', 'Sex']].loc[dados2['Sex'] == 'male']
print('Homens:',homens.shape)
print(homens.describe())
mulheres = dados2[['Survived', 'Sex']].loc[dados2['Sex'] == 'female']
print('Mulheres:',mulheres.shape)
print(mulheres.describe())

Homens: (577, 2)
         Survived
count  577.000000
mean     0.188908
std      0.391775
min      0.000000
25%      0.000000
50%      0.000000
75%      0.000000
max      1.000000
Mulheres: (314, 2)
         Survived
count  314.000000
mean     0.742038
std      0.438211
min      0.000000
25%      0.000000
50%      1.000000
75%      1.000000
max      1.000000


In [ ]:
criancas = dados2[['Survived', 'Age']].loc[dados2['Age'] < 16.0]
print('Crianças (até 15 anos):',criancas.shape)
print(criancas.describe())
naocriancas = dados2[['Survived', 'Age']].loc[dados2['Age'] >= 16.0]
print('Não crianças (acima de 15 anos):',naocriancas.shape)
print(naocriancas.describe())

Crianças (até 15 anos): (83, 2)
        Survived        Age
count  83.000000  83.000000
mean    0.590361   6.369518
std     0.494757   4.729063
min     0.000000   0.420000
25%     0.000000   2.000000
50%     1.000000   5.000000
75%     1.000000   9.500000
max     1.000000  15.000000
Não crianças (acima de 15 anos): (631, 2)
         Survived         Age
count  631.000000  631.000000
mean     0.381933   32.767829
std      0.486246   12.440732
min      0.000000   16.000000
25%      0.000000   23.000000
50%      0.000000   30.000000
75%      1.000000   40.000000
max      1.000000   80.000000


**Exercício:** Descubra a porcentagem de sobrevivência em cada classe social da base *Titanic* que importamos.

In [ ]:
classe1 = dados2[['Survived', 'Pclass']].loc[dados2['Pclass'] == 1]
print('Classe 1:',classe1.shape)
print(classe1.describe())
classe2 = dados2[['Survived', 'Pclass']].loc[dados2['Pclass'] == 2]
print('Classe 2:',classe2.shape)
print(classe2.describe())
classe3 = dados2[['Survived', 'Pclass']].loc[dados2['Pclass'] == 3]
print('Classe 3:',classe3.shape)
print(classe3.describe())

Classe 1: (216, 2)
         Survived  Pclass
count  216.000000   216.0
mean     0.629630     1.0
std      0.484026     0.0
min      0.000000     1.0
25%      0.000000     1.0
50%      1.000000     1.0
75%      1.000000     1.0
max      1.000000     1.0
Classe 2: (184, 2)
         Survived  Pclass
count  184.000000   184.0
mean     0.472826     2.0
std      0.500623     0.0
min      0.000000     2.0
25%      0.000000     2.0
50%      0.000000     2.0
75%      1.000000     2.0
max      1.000000     2.0
Classe 3: (491, 2)
         Survived  Pclass
count  491.000000   491.0
mean     0.242363     3.0
std      0.428949     0.0
min      0.000000     3.0
25%      0.000000     3.0
50%      0.000000     3.0
75%      0.000000     3.0
max      1.000000     3.0


**Vamos escrever para uma planilha???**

In [ ]:
classe1.to_excel('classe1.xlsx', index=False)
files.download('classe1.xlsx')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Um tipo especial de estrutura do Pandas, chamado *Series*, que tem a seguinte característica: assim como os *Dataframes*, está atrelada a um índice numérico. É como se fosse um *Dataframe*, só que de uma única coluna.

In [ ]:
s1 = pd.Series([2,5,3,34,54,23,1,16])
print(s1)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


In [ ]:
import numpy as np
array1 = np.array([2,5,3,34,54,23,1,16])
s2 = pd.Series(array1)
print(s2)

0     2
1     5
2     3
3    34
4    54
5    23
6     1
7    16
dtype: int64


In [ ]:
s3 = df1['Nome']
print(s3)
type(s3)

0    Marcelo
1      Lucas
2    Cynthia
3     Helena
Name: Nome, dtype: object


pandas.core.series.Series

**Detalhe:** Note que df1[['Nome']] é diferente de df1['Nome']

Consideraremos algumas manipulações com colunas de dataframes:

Quantas ocorrências (valores diferentes) em cada coluna:

In [ ]:
dados1['letras'].value_counts()

e    1
j    1
c    1
i    1
b    1
h    1
f    1
a    1
d    1
g    1
Name: letras, dtype: int64

Para a base do *Titanic*:

In [ ]:
dados2['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [ ]:
dados2['Age'].value_counts()

24.00    30
22.00    27
18.00    26
19.00    25
30.00    25
         ..
55.50     1
70.50     1
66.00     1
23.50     1
0.42      1
Name: Age, Length: 88, dtype: int64

Por último veremos como excluir uma coluna que pode não ser de nosso interesse com o *drop*. Temos que indicar qual a coluna alvo (no caso a “números”), que nosso alvo é uma
coluna (“axis=1”) e que não queremos mostrar os dados (“Inplace=True”):

In [ ]:
dados1.drop('números',axis=1,inplace=True)
print(dados1)

  letras
0      a
1      b
2      c
3      d
4      e
5      f
6      g
7      h
8      i
9      j


Retirar as linhas que tem dados faltantes com para
realizar alguma operação que pudesse depois trabalhar estes dados para conseguir completar
os dados NaN. Para fazer isso poderíamos usar:

In [ ]:
teste = dados1.dropna()
print(teste)

  letras
0      a
1      b
2      c
3      d
4      e
5      f
6      g
7      h
8      i
9      j


In [ ]:
teste2 = dados2.dropna()
print(teste2)

     PassengerId  Survived  Pclass  ...     Fare        Cabin  Embarked
1              2         1       1  ...  71.2833          C85         C
3              4         1       1  ...  53.1000         C123         S
6              7         0       1  ...  51.8625          E46         S
10            11         1       3  ...  16.7000           G6         S
11            12         1       1  ...  26.5500         C103         S
..           ...       ...     ...  ...      ...          ...       ...
871          872         1       1  ...  52.5542          D35         S
872          873         0       1  ...   5.0000  B51 B53 B55         S
879          880         1       1  ...  83.1583          C50         C
887          888         1       1  ...  30.0000          B42         S
889          890         1       1  ...  30.0000         C148         C

[183 rows x 12 columns]


Ao invés de excluí-los poderíamos verificar quais estão faltantes com a função “isnull”:

In [ ]:
nulos = dados1.isnull()
print(nulos)

   letras
0   False
1   False
2   False
3   False
4   False
5   False
6   False
7   False
8   False
9   False


In [ ]:
teste3 = dados2.isnull()
print(teste3)

     PassengerId  Survived  Pclass   Name  ...  Ticket   Fare  Cabin  Embarked
0          False     False   False  False  ...   False  False   True     False
1          False     False   False  False  ...   False  False  False     False
2          False     False   False  False  ...   False  False   True     False
3          False     False   False  False  ...   False  False  False     False
4          False     False   False  False  ...   False  False   True     False
..           ...       ...     ...    ...  ...     ...    ...    ...       ...
886        False     False   False  False  ...   False  False   True     False
887        False     False   False  False  ...   False  False  False     False
888        False     False   False  False  ...   False  False   True     False
889        False     False   False  False  ...   False  False  False     False
890        False     False   False  False  ...   False  False   True     False

[891 rows x 12 columns]


Usando o conceito do “isnull” podemos trabalhar a quantidade de dados faltantes:

In [ ]:
qtdnulos = dados1.isnull().sum()
print(qtdnulos)

letras    0
dtype: int64


In [ ]:
nulosTitanic = dados2.isnull().sum()
print(nulosTitanic)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


É possível também preencher os dados faltantes com algum valor. Por exemplo:

In [ ]:
dados1['letras'].fillna('semdados',inplace = True)
print(dados1)


  letras
0      a
1      b
2      c
3      d
4      e
5      f
6      g
7      h
8      i
9      j


In [ ]:
dados2['Cabin'].fillna('NA',inplace = True)
print(dados2)
nulosTitanic = dados2.isnull().sum()
print(nulosTitanic)

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500    NA         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250    NA         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500    NA         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000    NA         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500    NA         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500    NA         Q

[891 rows x 12 columns]
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin

**Exercícios:**

Teste estas manipulações com dataframes na base de dados do projeto (census.csv).

In [ ]:
#por exemplo....
dados3['native.country'].value_counts()


 United-States                 27504
 Mexico                          610
 Philippines                     188
 Germany                         128
 Puerto-Rico                     109
 Canada                          107
 India                           100
 El-Salvador                     100
 Cuba                             92
 England                          86
 Jamaica                          80
 South                            71
 Italy                            68
 China                            68
 Dominican-Republic               67
 Vietnam                          64
 Guatemala                        63
 Japan                            59
 Poland                           56
 Columbia                         56
 Haiti                            42
 Iran                             42
 Taiwan                           42
 Portugal                         34
 Nicaragua                        33
 Peru                             30
 Greece                           29
 